### ISSUE TITLE
Skapa Books

### ISSUE THREAD

**Issue by Sarvenaz83** [Sarvenaz83/HarryPotterAPI#4]
- [x] [Skapa BookDto](https://github.com/users/Sarvenaz83/projects/3/views/1?pane=issue&itemId=49806060)
- [x] Skapa GetAllBooksQuery
- [x] Skapa GetAllBobksQueryHabdler
- [x] [Skapa IBookRepository](https://github.com/users/Sarvenaz83/projects/3/views/1?pane=issue&itemId=49793064)
- [x] [Skapa BookRepository](https://github.com/users/Sarvenaz83/projects/3/views/1?pane=issue&itemId=49793022)
- [x] [Skapa BookValidator](https://github.com/users/Sarvenaz83/projects/3/views/1?pane=issue&itemId=49797962)
- [x] [Skapa GetAllBooksController](https://github.com/users/Sarvenaz83/projects/3/views/1?pane=issue&itemId=49793112)
- [x] Skapa några data i DataSeeder
- [x] Skapa GetAllBooksQueryHandlerTest

**Comment by MarkusFahlstrom** [comment]
All steps done and approved
